function [umat43Default, umat43Types] = getUmat43DefaultSettings(flag_0Nms_1kNmmms)

% Dimension Notation
% 	F: force
%	D: distance
%   T: time
%
%  'mid_unit'      ,  nan
%  'ro_unit'       ,  nan    
%  'mt_unit'       ,  nan
%  'lmc_unit'      ,  nan
%  'nhv_unit'      ,  nan
%  'iortho_unit'   ,  nan
%  'ibulk_unit'    ,  nan
%  'ig_unit'       ,  nan
%  'ivect_unit'    ,  nan
%  'ifail_unit'    ,  nan
%  'itherm_unit'   ,  nan
%  'ihyper_unit'   ,  nan
%  'ieos_unit'     ,  nan
%  'lmca_unit'     ,  nan
%  'unused_unit'   ,  nan
%  'unused_unit'   ,  nan
%  'stimId_unit'   ,  nan
%  'tauAct_unit'   ,  From Millard et al. 2012 Eqn. 2, with amin=0
%			da/dt	=     (e-a)/tau, 
%       	 tau 	=     (e-a)/(da/dt)
% 		unit(tau)	=unit((e-a)/(da/dt)), 
%                   = Time
%  'tauDeact_unit'  = Time
%  'fceOptIso_unit',  F
%  'lceOpt_unit'   ,  D
%  'alphaOptD_unit',  nan           
%  'ltSlk_unit'    ,  D
%  'etIso_unit'    ,  nan        
%  'dtN_unit'      ,  ftN = fteN(ltN) + U*kteN(ltN)*vTN
%                     U = (ftN-fteN(ltN))/(kteN(ltN)*vTN)
%                unit(U)= (F/F - F/F)/( (dF/F)/(dL/L)*(D/T)/(D)  )
%                       = (-)/((-)/(-) * (1/T)  )
%                       = Time
%  'scalePEE_unit' ,  nan          
%
%  'lambdaECM_unit',  nan         
%
%  'beta1AHN_unit' ,  dl1N/dt = (F2N-F1N)/beta,                 Eqn. 18 of Millard, Franklin, Herzog
%            unit(beta) = unit(F2N-F1N)/unit(dl1N/dt)
%            unit(beta) = (F/F - F/F)/((L/T)/L)
%            unit(beta) = (-)/(1/T)
%                       = Time
%
%  'beta1PHN_unit' ,  Time (as in beta1AHN_unit)             
%
%
% Eqn 15 of Millard, Franklin, Herzog
%
%	fMN = a*fLN*(kxN*lxN+bxN*vxN) + f2N + fecmN + betaN*vM
%
%  'kxOptIsoN_unit',  
%
%
%  'dxOptIsoN_unit',  '(N/N)/((m/s)/(m/s))             = -'            Eqn. 15
%  						: dimensionless
%  'gainTrack_pos_unit',  '((m/s^2)/(m/s))/(m/m)       = 1/s'          Eqn. 16  
%						: 1/Time
%  'gainTrack_vel_unit',  '((m/s^2)/(m/s))/((m/s)/(m/s)= 1/s'          Eqn. 16  
%  						: 1/Time
%
%  'vceMax_unit'   ,  '(m/s)/m                         = 1/s'          
%                  		: 1/Time
%  'taudvst_unit'  ,   Eqn. 16
%
%        
%  'dvsBeta_unit'  ,  '((m/s^2)/(m/s) / ((m/s)/(m/s))  = 1/s'          Eqn. 16
%  'aniType_unit'  ,  nan
%  'ctlType_unit' ,  nan
%  'ctlDelay_unit',  s          
%  'ctlThrsh_unit',  nan       
%  'output_unit'   ,  nan
%  'dtout_unit'    ,  nan

%     'mid'        'ro'        'mt'       'lmc'       'nhv'    'iortho'  'ibulkIdx'     'igIdx'
%   'ivect'     'ifail'    'itherm'    'ihyper'      'ieos'      'lmca'    'unused'    'unused'
%  'stimId' 'exDefault'    'tauAct'  'tauDeact' 'fceOptIso'    'lceOpt' 'alphaOptD' 'useRgdTdn'
%   'ltSlk'     'etIso'       'dtN'  'scalePEE' 'lambdaECM'  'lPevkPtN' 'lceHNLb1A'   'act1AHN'
%'beta1AHN'  'beta1PHN' 'kxOptIsoN' 'dxOptIsoN' 'gainTrack'  'actTrack'    'vceMax'   'taudvst'
% 'dvsBeta'    'dtNumN'   'aniType'   'ctlType'  'ctlDelay'  'ctlThrsh' 'ctlOnTime'    'output'
%   'dtout'     'IBULK'        'IG'   

umat43Default=[];

switch flag_0Nms_1kNmmms

	case 0
		%Units of N, m, s
		umat43Default = struct(      ...
				'mid'      ,  1     ,...  
				'ro'       ,  1.e-6 ,...    
				'mt'       ,  43    ,...    
				'lmc'      ,  34    ,...     
				'nhv'      ,  1000  ,...        
				'iortho'   ,  0     ,...     
				'ibulkIdx' ,  29    ,...     
				'igIdx'    ,  30    ,...     
				'ivect'    ,  0     ,...     
				'ifail'    ,  0     ,...    
				'itherm'   ,  0     ,...     
				'ihyper'   ,  0     ,...     
				'ieos'     ,  0     ,...     
				'lmca'     ,  0     ,...     
				'unused0'   ,  ''    ,...      
				'unused1'   ,  ''    ,...      
					'stimId'   ,  nan   ,...     
					'exDefault',  0     ,...  
					'tauAct'   ,  0.01  ,...        
					'tauDeact' ,  0.04  ,...        
					'fceOptIso',  nan   ,...       
					'lceOpt'   ,  nan   ,...       
					'alphaOptD',  0.    ,...   
					'useRgdTdn',  0     ,...   
				'ltSlk'    ,  nan   ,...       
				'etIso'    ,  0.049 ,...         
				'dtN'      ,  0.0556,...          
				'scalePEE' ,  1.0   ,...       
				'lambdaECM',  0.56  ,...  
				'lPevkPtN' ,  0.50  ,...        
				'lceHNLb1A',  0.40  ,...   
				'act1AHN'  ,  0.10  ,...
					'beta1AHN' ,  65    ,...
					'beta1PHN' ,  0.25  ,...  
					'kxOptIsoN',  47.8  ,...        
					'dxOptIsoN',  0.354 ,...         
					'gainTrk'  ,  1000. ,... 
					'actTrk'   ,  0.05  ,...      
					'vceMax'   ,  10.0  ,...        
					'taudvst'  ,  1.0e-3,...          
				'dvsBeta'  ,  1.0   ,...
				'dtNumN'   ,  0.0001,...        
				'aniType'  ,  0     ,...
				'ctlType'    ,  3     ,... 
				'ctlDelay'   ,  '&dly' ,...
				'ctlThrsh'   ,  '&thm'  ,...
				'ctlOnTime'  ,  '&ctlOnTime' ,...
				'output'   ,  1     ,...     
				'dtout'    ,  0.001 ,...
                	'IBULK'    ,  0.13  ,...
                	'IG'       ,  0.13);

		structFields = fields(umat43Default);
		numberOfFields = length(structFields);
		umat43Default.lmc = numberOfFields - 16;


	case 1
		%Units of kN, mm, ms
		umat43Default = struct(        ...
			    'mid'      ,  1       ,... 
				'ro'       ,  1.e-6   ,...   
				'mt'       ,  43      ,...   
				'lmc'      ,  34      ,...    
				'nhv'      ,  1000    ,...       
				'iortho'   ,  0       ,...    
				'ibulkIdx' ,  29      ,...    
				'igIdx'    ,  30      ,...    
				'ivect'    ,  0       ,...    
				'ifail'    ,  0       ,...   
				'itherm'   ,  0       ,...    
				'ihyper'   ,  0       ,...    
				'ieos'     ,  0       ,...    
				'lmca'     ,  0       ,...    
				'unused0'   ,  ''     ,...     
				'unused1'   ,  ''     ,...     
					'stimId'   ,  nan     ,...  
					'exDefault',  0       ,...  				    
					'tauAct'   ,  10      ,...     
					'tauDeact' ,  40      ,...     
					'fceOptIso',  nan     ,...      
					'lceOpt'   ,  nan     ,...      
					'alphaOptD',  0.      ,... 
					'useRgdTdn',  0       ,...				    
				'ltSlk'    ,  nan     ,...      
				'etIso'    ,  0.049   ,...        
				'dtN'      ,  55.6  ,...         
				'scalePEE' ,  1.0     ,...      
				'lambdaECM',  0.56    ,...  
				'lPevkPtN' ,  0.50  ,...        
				'lceHNLb1A',  0.40  ,...   
				'act1AHN'  ,  0.10  ,...     
					'beta1AHN' ,  65000   ,...  
					'beta1PHN' ,  250     ,...               
					'kxOptIsoN',  47.8    ,...       
					'dxOptIsoN',  0.354   ,...          
					'gainTrk',    0.001   ,...    
					'actTrk',     0.05    ,...
					'vceMax'   ,  0.01    ,...      
					'taudvst'  ,  1000.0  ,...     
				'dvsBeta'  ,  1.0e-3  ,...
				'dtNumN'   ,  0.1 	  ,...        
				'aniType'  ,  0       ,...   
				'ctlType'    ,  3       ,... 
				'ctlDelay'   ,  '&cDly'   ,...
				'ctlThrsh'   ,  '&cThr'   ,...   
				'ctlOnTime'  ,  '&cOnTime',...  				
				'output'   ,  1       ,...   
				'dtout'    ,  1       ,...
                	'IBULK'    ,  0.13    ,...
                	'IG'       ,  0.13);

		structFields = fields(umat43Default);
		numberOfFields = length(structFields);
		umat43Default.lmc = numberOfFields - 16;

end

umat43Types = struct(      ...
	    'mid'      ,  '%i' ,... 
		'ro'       ,  '%e' ,...   
		'mt'       ,  '%i' ,...   
		'lmc'      ,  '%i' ,...    
		'nhv'      ,  '%i' ,...       
		'iortho'   ,  '%i' ,...    
		'ibulkIdx' ,  '%i' ,...    
		'igIdx'    ,  '%i' ,...    
		'ivect'    ,  '%i' ,...    
		'ifail'    ,  '%i' ,...   
		'itherm'   ,  '%i' ,...    
		'ihyper'   ,  '%i' ,...    
		'ieos'     ,  '%i' ,...    
		'lmca'     ,  '%i' ,...    
		'unused0'   ,  ''  ,...     
		'unused1'   ,  ''  ,...     
			'stimId'   ,  '%i' ,... 
			'exDefault',  '%e' ,...  		     
			'tauAct'   ,  '%e' ,...     
			'tauDeact' ,  '%e' ,...     
			'fceOptIso',  '%e' ,...      
			'lceOpt'   ,  '%e' ,...      
			'alphaOptD',  '%e' ,... 
			'useRgdTdn',  '%i' ,...    
		'ltSlk'    ,  '%e' ,...      
		'etIso'    ,  '%e' ,...        
		'dtN'      ,  '%e' ,...         
		'scalePEE' ,  '%e' ,...      
		'lambdaECM',  '%e' ,...     
		'lPevkPtN' ,  '%e'  ,...        
		'lceHNLb1A',  '%e'  ,...   
		'act1AHN'  ,  '%e'  ,...     		  
			'beta1AHN' ,  '%e' ,...    
			'beta1PHN' ,  '%e' ,...          
			'kxOptIsoN',  '%e' ,...       
			'dxOptIsoN',  '%e' ,...          
			'gainTrk',    '%e' ,...     
			'actTrk',     '%e' ,...
			'vceMax'   ,  '%e' ,...      
			'taudvst'  ,  '%e' ,...     
		'dvsBeta'  ,  '%e' ,... 
		'dtNumN'   ,  '%e' ,...       
		'aniType'  ,  '%i' ,...   
		'ctlType'    ,  '%i' ,... 
        'ctlDelay' ,    '%s' ,... 
		'ctlThrsh' ,    '%s' ,...
		'ctlOnTime',    '%s',...     
		'output'   ,  '%i' ,...   
		'dtout'    ,  '%e' ,...
        	'IBULK'    ,  '%e' ,...
        	'IG'       ,  '%e' );
